version: '3.8'

services:
  goapp:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    container_name: go-cloudrun
    ports:
      - 8080:8080
    environment:
      - APP_ENV=production